--- testBaseExceptionGold	2011-04-27 13:11:55.000000000 -0400
+++ testBaseException	2011-12-12 08:58:22.000000000 -0500
@@ -1,37 +1,46 @@
+
+
+There is a logic_error
+
+On line 68 of ../testBaseException.cpp
+../bin/linux-x86/testBaseException[0x80497b9]
+../bin/linux-x86/testBaseException[0x8049a54]
+/lib/libc.so.6(__libc_start_main+0xe6)[0x126e36]
+../bin/linux-x86/testBaseException[0x80490e1]
+To translate run 'addr2line -e execname 0xXXXXXXX ...'
+  Note: Must be compiled with debug symbols
+
+
+There is another logic_error
+
+On line 75 of ../testBaseException.cpp
+../bin/linux-x86/testBaseException() [0x8049cec]
+../bin/linux-x86/testBaseException() [0x8049923]
+../bin/linux-x86/testBaseException() [0x8049a54]
+/lib/libc.so.6(__libc_start_main+0xe6) [0x126e36]
+../bin/linux-x86/testBaseException() [0x80490e1]
+
 testBaseException... 
 
 all is OK
-	at ../testBaseException.cpp:48
-	   ../bin/linux-x86/testBaseException
-	   ../bin/linux-x86/testBaseException
-	   /lib/libc.so.6: __libc_start_main()+0xe6
-	   ../bin/linux-x86/testBaseException
+On line 48 of ../testBaseException.cpp
+../bin/linux-x86/testBaseException() [0x8049581]
+../bin/linux-x86/testBaseException() [0x8049a5c]
+/lib/libc.so.6(__libc_start_main+0xe6) [0x126e36]
+../bin/linux-x86/testBaseException() [0x80490e1]
+
 
 
 
 
 exception 2
-	at ../testBaseException.cpp:57
-	   ../bin/linux-x86/testBaseException
-	   ../bin/linux-x86/testBaseException
-	   ../bin/linux-x86/testBaseException
-	   /lib/libc.so.6: __libc_start_main()+0xe6
-	   ../bin/linux-x86/testBaseException
-exception 1
-	at ../testBaseException.cpp:40
-	   ../bin/linux-x86/testBaseException
-	   ../bin/linux-x86/testBaseException
-	   ../bin/linux-x86/testBaseException
-	   ../bin/linux-x86/testBaseException
-	   /lib/libc.so.6: __libc_start_main()+0xe6
-	   ../bin/linux-x86/testBaseException
-the root cause
-	at ../testBaseException.cpp:31
-	   ../bin/linux-x86/testBaseException
-	   ../bin/linux-x86/testBaseException
-	   ../bin/linux-x86/testBaseException
-	   /lib/libc.so.6: __libc_start_main()+0xe6
-	   ../bin/linux-x86/testBaseException
+On line 57 of ../testBaseException.cpp
+../bin/linux-x86/testBaseException() [0x80491ec]
+../bin/linux-x86/testBaseException() [0x80496f9]
+../bin/linux-x86/testBaseException() [0x8049a5c]
+/lib/libc.so.6(__libc_start_main+0xe6) [0x126e36]
+../bin/linux-x86/testBaseException() [0x80490e1]
+
 
 
 PASSED
