--- testBaseExceptionGold	2012-01-21 13:09:44.864000461 -0500
+++ testBaseException	2012-07-19 16:06:11.418991443 -0400
@@ -1,37 +1,45 @@
+
+
+There is a logic_error
+
+On line 68 of ../testBaseException.cpp
+../bin/linux-x86_64/testBaseException[0x401abb]
+../bin/linux-x86_64/testBaseException[0x4014b4]
+/lib64/libc.so.6(__libc_start_main+0xed)[0x300ea2169d]
+../bin/linux-x86_64/testBaseException[0x40150d]
+To translate run 'addr2line -e execname 0xXXXXXXX ...'
+  Note: Must be compiled with debug symbols
+
+
+There is another logic_error
+
+On line 75 of ../testBaseException.cpp
+../bin/linux-x86_64/testBaseException() [0x401c79]
+../bin/linux-x86_64/testBaseException() [0x4014b4]
+/lib64/libc.so.6(__libc_start_main+0xed) [0x300ea2169d]
+../bin/linux-x86_64/testBaseException() [0x40150d]
+
 testBaseException... 
 
 all is OK
-	at ../testBaseException.cpp:48
-	   ../bin/linux-x86/testBaseException
-	   ../bin/linux-x86/testBaseException
-	   /lib/libc.so.6: __libc_start_main()+0xe6
-	   ../bin/linux-x86/testBaseException
+On line 48 of ../testBaseException.cpp
+../bin/linux-x86_64/testBaseException() [0x401859]
+../bin/linux-x86_64/testBaseException() [0x4014bc]
+/lib64/libc.so.6(__libc_start_main+0xed) [0x300ea2169d]
+../bin/linux-x86_64/testBaseException() [0x40150d]
+
 
 
 
 
 exception 2
-	at ../testBaseException.cpp:57
-	   ../bin/linux-x86/testBaseException
-	   ../bin/linux-x86/testBaseException
-	   ../bin/linux-x86/testBaseException
-	   /lib/libc.so.6: __libc_start_main()+0xe6
-	   ../bin/linux-x86/testBaseException
-exception 1
-	at ../testBaseException.cpp:40
-	   ../bin/linux-x86/testBaseException
-	   ../bin/linux-x86/testBaseException
-	   ../bin/linux-x86/testBaseException
-	   ../bin/linux-x86/testBaseException
-	   /lib/libc.so.6: __libc_start_main()+0xe6
-	   ../bin/linux-x86/testBaseException
-the root cause
-	at ../testBaseException.cpp:31
-	   ../bin/linux-x86/testBaseException
-	   ../bin/linux-x86/testBaseException
-	   ../bin/linux-x86/testBaseException
-	   /lib/libc.so.6: __libc_start_main()+0xe6
-	   ../bin/linux-x86/testBaseException
+On line 57 of ../testBaseException.cpp
+../bin/linux-x86_64/testBaseException() [0x40162c]
+../bin/linux-x86_64/testBaseException() [0x401a10]
+../bin/linux-x86_64/testBaseException() [0x4014bc]
+/lib64/libc.so.6(__libc_start_main+0xed) [0x300ea2169d]
+../bin/linux-x86_64/testBaseException() [0x40150d]
+
 
 
 PASSED
