

There is a logic_error

On line 68 of ../testBaseException.cpp
../bin/linux-x86_64/testBaseException[0x401abb]
../bin/linux-x86_64/testBaseException[0x4014b4]
/lib64/libc.so.6(__libc_start_main+0xed)[0x366dc2169d]
../bin/linux-x86_64/testBaseException[0x40150d]
To translate run 'addr2line -e execname 0xXXXXXXX ...'
  Note: Must be compiled with debug symbols


There is another logic_error

On line 75 of ../testBaseException.cpp
../bin/linux-x86_64/testBaseException() [0x401c79]
../bin/linux-x86_64/testBaseException() [0x4014b4]
/lib64/libc.so.6(__libc_start_main+0xed) [0x366dc2169d]
../bin/linux-x86_64/testBaseException() [0x40150d]

testBaseException... 

all is OK
On line 48 of ../testBaseException.cpp
../bin/linux-x86_64/testBaseException() [0x401859]
../bin/linux-x86_64/testBaseException() [0x4014bc]
/lib64/libc.so.6(__libc_start_main+0xed) [0x366dc2169d]
../bin/linux-x86_64/testBaseException() [0x40150d]





exception 2
On line 57 of ../testBaseException.cpp
../bin/linux-x86_64/testBaseException() [0x40162c]
../bin/linux-x86_64/testBaseException() [0x401a10]
../bin/linux-x86_64/testBaseException() [0x4014bc]
/lib64/libc.so.6(__libc_start_main+0xed) [0x366dc2169d]
../bin/linux-x86_64/testBaseException() [0x40150d]



PASSED
